/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: OSCAR CREATIVO (https://sketchfab.com/oscar_creativo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-cartoon-cute-by-oscar-creativo-254bd1caa4d54300a625120913cf4cd7
Title: CAT CARTOON CUTE BY Oscar Creativo
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

import scene from "../assets/3d/cat.glb";

export function Cat({ currentAnimation, animationSpeed, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
      actions[currentAnimation].timeScale = animationSpeed;
    }
  }, [actions, currentAnimation, animationSpeed]);

  useFrame((state, delta) => {
    mixer.update(delta);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[1.576, 0, 0]} scale={1.628}>
          <group
            name="8a2b434acdde4265ac5d82091f90c73ffbx"
            rotation={[-Math.PI, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Lower_Teeth}
                    skeleton={nodes.Object_7.skeleton}
                    morphTargetDictionary={nodes.Object_7.morphTargetDictionary}
                    morphTargetInfluences={nodes.Object_7.morphTargetInfluences}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Upper_Teeth}
                    skeleton={nodes.Object_8.skeleton}
                    morphTargetDictionary={nodes.Object_8.morphTargetDictionary}
                    morphTargetInfluences={nodes.Object_8.morphTargetInfluences}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.Tongue}
                    skeleton={nodes.Object_9.skeleton}
                    morphTargetDictionary={nodes.Object_9.morphTargetDictionary}
                    morphTargetInfluences={nodes.Object_9.morphTargetInfluences}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.Arms}
                    skeleton={nodes.Object_10.skeleton}
                    morphTargetDictionary={
                      nodes.Object_10.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Object_10.morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.Legs}
                    skeleton={nodes.Object_11.skeleton}
                    morphTargetDictionary={
                      nodes.Object_11.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Object_11.morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.Head}
                    skeleton={nodes.Object_12.skeleton}
                    morphTargetDictionary={
                      nodes.Object_12.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Object_12.morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.Socket}
                    skeleton={nodes.Object_13.skeleton}
                    morphTargetDictionary={
                      nodes.Object_13.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Object_13.morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.Torso}
                    skeleton={nodes.Object_14.skeleton}
                    morphTargetDictionary={
                      nodes.Object_14.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Object_14.morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials.Sclera}
                    skeleton={nodes.Object_15.skeleton}
                    morphTargetDictionary={
                      nodes.Object_15.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Object_15.morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials.Mouth}
                    skeleton={nodes.Object_16.skeleton}
                    morphTargetDictionary={
                      nodes.Object_16.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Object_16.morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials.Moisture}
                    skeleton={nodes.Object_17.skeleton}
                    morphTargetDictionary={
                      nodes.Object_17.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Object_17.morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_18"
                    geometry={nodes.Object_18.geometry}
                    material={materials.Claws}
                    skeleton={nodes.Object_18.skeleton}
                    morphTargetDictionary={
                      nodes.Object_18.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Object_18.morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials.Body}
                    skeleton={nodes.Object_20.skeleton}
                  />
                  <skinnedMesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    material={materials.Switch}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    name="Object_22"
                    geometry={nodes.Object_22.geometry}
                    material={materials.EarPad}
                    skeleton={nodes.Object_22.skeleton}
                  />
                  <skinnedMesh
                    name="Object_23"
                    geometry={nodes.Object_23.geometry}
                    material={materials.Boom}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    name="Object_24"
                    geometry={nodes.Object_24.geometry}
                    material={materials.Display}
                    skeleton={nodes.Object_24.skeleton}
                  />
                  <skinnedMesh
                    name="Object_25"
                    geometry={nodes.Object_25.geometry}
                    material={materials.LensDial}
                    skeleton={nodes.Object_25.skeleton}
                  />
                  <skinnedMesh
                    name="Object_26"
                    geometry={nodes.Object_26.geometry}
                    material={materials.Lens}
                    skeleton={nodes.Object_26.skeleton}
                  />
                  <skinnedMesh
                    name="Object_27"
                    geometry={nodes.Object_27.geometry}
                    material={materials.Infomations}
                    skeleton={nodes.Object_27.skeleton}
                  />
                  <skinnedMesh
                    name="Object_28"
                    geometry={nodes.Object_28.geometry}
                    material={materials.Decal}
                    skeleton={nodes.Object_28.skeleton}
                  />
                  <group name="Object_6" />
                  <group name="Object_19" />
                  <group name="Catoon_10074_Shape" />
                  <group name="Scouter_Editable_Normal" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
